server:
  port: 8089
spring:
  datasource:
     url: jdbc:h2:mem:testIncidentDB
     driverClassName: org.h2.Driver
     username: sa
     password: password
  sql:
    init.mode: always
  jpa:
     defer-datasource-initialization: true
     show-sql: true
     properties:
       hibernate:
         format_sql: true
         show-sql: true
     hibernate:
       ddl-auto: create-drop
  application:
    name: incident-management-service
#eureka:
#  instance:
#    hostname: ${vcap.application.uris[0]:localhost}
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
#    leaseRenewalIntervalInSeconds: 5
#  client:
#    region: default
#    registryFetchIntervalSeconds: 5
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

application:
  title: incident-management-service
  version: 1.0